---
title: "Lab6"
author: "Разаков Дамир БИСО-03-20"
format: 
    md:
        output-file: Lab6.md
editor: visual
---

#Применение средств и методов OSINT

##Цель работы

1.  Освоить базовые подходы процессов OSINT

2.  Освоить современные инструменты поиска и сбора информации

3.  Освоить инструменты совместной работы в ходе аналитической деятельности

##План выполнения

1.  Собрать информацию о профильных компаниях в сфере ИБ и их продуктах

2.  Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.

3.  Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4.  Сформировать представление о рынке отечественных решений ИБ

##Ход работы

Собрать публичную информацию об компании Swordfish Security

1.  Название ООО "Свордфиш Секьюрити" - Создание защищенных приложений, адаптируя и тиражируя практики SSDL.

    Их применение гарантирует премиальный уровень защищенности ПО, а максимальная автоматизация процессов при помощи инструментального стека DevSecOps обеспечивает эффективность инженерного процесса разработки.

    С 2020 года входит в Группу Компаний Swordfish

2.  Другие компании Группы: Swordfish Distribution, AppSec Solutions, Стрингрей Технолоджиз

3.  Основные направляения деятельности компании:

    1.  Сервисы:
        1.  Анализ защищенности программного обеспечения
        2.  Разработка стратегии внедрения практик Application Security
        3.  Сервис онбординга приложения в контур SSDL
        4.  Построение процесса DevSecOps
        5.  Технологический консалтинг
        6.  Процессный консалтинг DevSecOps
        7.  Архитектурный консалтинг
        8.  Построение центра компетенций
    2.  Продукты:
        1.  AppSec.Hub --- платформа DevSecOps. Используется в бизнесе, ИБ и при разработке ПО. Основные достоинства: Автоматизация процесса от начала и до конца, Полная прозрачность, Исключение False Positives, Масштабируемая интеграция.
        2.  Стингрей --- система динамического анализа мобильных приложений. Система предназначена для руководителей ИТ, руководителей отделов разработки и тестирования, разработчиков, аналитиков безопасности и тестировщиков. Основные достоинства: Автоматизация поиска уязвимостей, рекомендации по устранению найденных уязвимостей, проверка приложений на стандарты ИБ, экономия ресурсов, гибкие форматы внедрения и модели лицензирования
    3.  Технологический стек:
        1.  Java
        2.  Angular
        3.  Python
        4.  PostgreSQL

4.  Клиенты:

    1.  ВТБ
    2.  Альфа Страхование
    3.  Яндекс
    4.  Домклик Сбер
    5.  Сбер Страхование
    6.  Почта России
    7.  ГазПроБанк
    8.  СберБанк
    9.  АльфаБанк
    10. РоссельхозБанк
    11. Тинькофф
    12. АкБарсБанк
    13. НСПК
    14. ПСБ
    15. Quadcode
    16. HeadHunter
    17. bpc

5.  Сайты:

    1.  https://swordfishsecurity.ru

    2.  https://stingray-mobile.ru

    3.  https://appsec-hub.ru

6.  Публичные сотрудники:

    1.  Юрий Шабалин, ведущий архитектор ИБ

        1.  Application Security эксперт с опытом более 8 лет в области внедрения практик SSDL, построения процессов SecDevOps;

        2.  Экспертное знание развивающегося рынка технологического стека Application Security, профессиональное владение инструментами классов SAST/DAST/IAST/SCA;

        3.  Спикер международных конференций по Информационной Безопасности. Автор тренингов по процессам и практикам разработки защищенного ПО;

        4.  Автор статей по машинному обучению и нейронным сетям

    2.  Светлана Газизова, руководитель направления аудита и консалтинга в области безопасной разработки Swordfish Security

        1.  Выступление на конференции "Безопасная разработка". В офлайн-формате по адресу --- Москва, Крокус Конгресс Холл, павильон 3, зал 20

        2.  Статья на хабр(https://habr.com/ru/companies/swordfish_security/articles/729128/)

    3.  Антон Башарин( глава разработки AppSec.Hub) https://www.youtube.com/watch?v=pBjldPX6Gtk&t=2s

    4.  Контактные лица:

        1.  Ксения Хаустова (HR)

        2.  Андрей Красовский (Креативный Директор)

    5.  Генеральный директор: Пинаев Александр Владимирович
